<?php
/**
 * AbsoluteDirection
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenBitApp\OTPClient\Model;
use \OpenBitApp\OTPClient\ObjectSerializer;

/**
 * AbsoluteDirection Class Doc Comment
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AbsoluteDirection
{
    /**
     * Possible values of this enum
     */
    const NORTH = 'NORTH';

    const NORTHEAST = 'NORTHEAST';

    const EAST = 'EAST';

    const SOUTHEAST = 'SOUTHEAST';

    const SOUTH = 'SOUTH';

    const SOUTHWEST = 'SOUTHWEST';

    const WEST = 'WEST';

    const NORTHWEST = 'NORTHWEST';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NORTH,
            self::NORTHEAST,
            self::EAST,
            self::SOUTHEAST,
            self::SOUTH,
            self::SOUTHWEST,
            self::WEST,
            self::NORTHWEST
        ];
    }
}


