<?php
/**
 * Message
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenBitApp\OTPClient\Model;
use \OpenBitApp\OTPClient\ObjectSerializer;

/**
 * Message Class Doc Comment
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Message
{
    /**
     * Possible values of this enum
     */
    const PLAN_OK = 'PLAN_OK';

    const SYSTEM_ERROR = 'SYSTEM_ERROR';

    const GRAPH_UNAVAILABLE = 'GRAPH_UNAVAILABLE';

    const OUTSIDE_BOUNDS = 'OUTSIDE_BOUNDS';

    const PATH_NOT_FOUND = 'PATH_NOT_FOUND';

    const NO_TRANSIT_TIMES = 'NO_TRANSIT_TIMES';

    const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';

    const BOGUS_PARAMETER = 'BOGUS_PARAMETER';

    const GEOCODE_FROM_NOT_FOUND = 'GEOCODE_FROM_NOT_FOUND';

    const GEOCODE_TO_NOT_FOUND = 'GEOCODE_TO_NOT_FOUND';

    const GEOCODE_FROM_TO_NOT_FOUND = 'GEOCODE_FROM_TO_NOT_FOUND';

    const TOO_CLOSE = 'TOO_CLOSE';

    const LOCATION_NOT_ACCESSIBLE = 'LOCATION_NOT_ACCESSIBLE';

    const GEOCODE_FROM_AMBIGUOUS = 'GEOCODE_FROM_AMBIGUOUS';

    const GEOCODE_TO_AMBIGUOUS = 'GEOCODE_TO_AMBIGUOUS';

    const GEOCODE_FROM_TO_AMBIGUOUS = 'GEOCODE_FROM_TO_AMBIGUOUS';

    const UNDERSPECIFIED_TRIANGLE = 'UNDERSPECIFIED_TRIANGLE';

    const TRIANGLE_NOT_AFFINE = 'TRIANGLE_NOT_AFFINE';

    const TRIANGLE_OPTIMIZE_TYPE_NOT_SET = 'TRIANGLE_OPTIMIZE_TYPE_NOT_SET';

    const TRIANGLE_VALUES_NOT_SET = 'TRIANGLE_VALUES_NOT_SET';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PLAN_OK,
            self::SYSTEM_ERROR,
            self::GRAPH_UNAVAILABLE,
            self::OUTSIDE_BOUNDS,
            self::PATH_NOT_FOUND,
            self::NO_TRANSIT_TIMES,
            self::REQUEST_TIMEOUT,
            self::BOGUS_PARAMETER,
            self::GEOCODE_FROM_NOT_FOUND,
            self::GEOCODE_TO_NOT_FOUND,
            self::GEOCODE_FROM_TO_NOT_FOUND,
            self::TOO_CLOSE,
            self::LOCATION_NOT_ACCESSIBLE,
            self::GEOCODE_FROM_AMBIGUOUS,
            self::GEOCODE_TO_AMBIGUOUS,
            self::GEOCODE_FROM_TO_AMBIGUOUS,
            self::UNDERSPECIFIED_TRIANGLE,
            self::TRIANGLE_NOT_AFFINE,
            self::TRIANGLE_OPTIMIZE_TYPE_NOT_SET,
            self::TRIANGLE_VALUES_NOT_SET
        ];
    }
}


