<?php
/**
 * OTPPlanResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenBitApp\OTPClient\Model;

use \ArrayAccess;
use \OpenBitApp\OTPClient\ObjectSerializer;

/**
 * OTPPlanResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenBitApp\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OTPPlanResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OTPPlanResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'debug_output' => '\OpenBitApp\OTPClient\Model\DebugOutput',
        'elevation_metadata' => '\OpenBitApp\OTPClient\Model\ElevationMetadata',
        'plan' => '\OpenBitApp\OTPClient\Model\TripPlan',
        'error' => '\OpenBitApp\OTPClient\Model\PlannerError',
        'request_parameters' => '\OpenBitApp\OTPClient\Model\RequestParameters'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'debug_output' => null,
        'elevation_metadata' => null,
        'plan' => null,
        'error' => null,
        'request_parameters' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'debug_output' => 'debugOutput',
        'elevation_metadata' => 'elevationMetadata',
        'plan' => 'plan',
        'error' => 'error',
        'request_parameters' => 'requestParameters'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'debug_output' => 'setDebugOutput',
        'elevation_metadata' => 'setElevationMetadata',
        'plan' => 'setPlan',
        'error' => 'setError',
        'request_parameters' => 'setRequestParameters'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'debug_output' => 'getDebugOutput',
        'elevation_metadata' => 'getElevationMetadata',
        'plan' => 'getPlan',
        'error' => 'getError',
        'request_parameters' => 'getRequestParameters'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['debug_output'] = $data['debug_output'] ?? null;
        $this->container['elevation_metadata'] = $data['elevation_metadata'] ?? null;
        $this->container['plan'] = $data['plan'] ?? null;
        $this->container['error'] = $data['error'] ?? null;
        $this->container['request_parameters'] = $data['request_parameters'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['debug_output'] === null) {
            $invalidProperties[] = "'debug_output' can't be null";
        }
        if ($this->container['elevation_metadata'] === null) {
            $invalidProperties[] = "'elevation_metadata' can't be null";
        }
        if ($this->container['request_parameters'] === null) {
            $invalidProperties[] = "'request_parameters' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets debug_output
     *
     * @return \OpenBitApp\OTPClient\Model\DebugOutput
     */
    public function getDebugOutput()
    {
        return $this->container['debug_output'];
    }

    /**
     * Sets debug_output
     *
     * @param \OpenBitApp\OTPClient\Model\DebugOutput $debug_output debug_output
     *
     * @return self
     */
    public function setDebugOutput($debug_output)
    {
        $this->container['debug_output'] = $debug_output;

        return $this;
    }

    /**
     * Gets elevation_metadata
     *
     * @return \OpenBitApp\OTPClient\Model\ElevationMetadata
     */
    public function getElevationMetadata()
    {
        return $this->container['elevation_metadata'];
    }

    /**
     * Sets elevation_metadata
     *
     * @param \OpenBitApp\OTPClient\Model\ElevationMetadata $elevation_metadata elevation_metadata
     *
     * @return self
     */
    public function setElevationMetadata($elevation_metadata)
    {
        $this->container['elevation_metadata'] = $elevation_metadata;

        return $this;
    }

    /**
     * Gets plan
     *
     * @return \OpenBitApp\OTPClient\Model\TripPlan|null
     */
    public function getPlan()
    {
        return $this->container['plan'];
    }

    /**
     * Sets plan
     *
     * @param \OpenBitApp\OTPClient\Model\TripPlan|null $plan plan
     *
     * @return self
     */
    public function setPlan($plan)
    {
        $this->container['plan'] = $plan;

        return $this;
    }

    /**
     * Gets error
     *
     * @return \OpenBitApp\OTPClient\Model\PlannerError|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param \OpenBitApp\OTPClient\Model\PlannerError|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets request_parameters
     *
     * @return \OpenBitApp\OTPClient\Model\RequestParameters
     */
    public function getRequestParameters()
    {
        return $this->container['request_parameters'];
    }

    /**
     * Sets request_parameters
     *
     * @param \OpenBitApp\OTPClient\Model\RequestParameters $request_parameters request_parameters
     *
     * @return self
     */
    public function setRequestParameters($request_parameters)
    {
        $this->container['request_parameters'] = $request_parameters;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


