<?php
/**
 * ElevationTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  BitappSrl\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BitappSrl\OTPClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ElevationTest Class Doc Comment
 *
 * @category    Class
 * @description Elevation
 * @package     BitappSrl\OTPClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ElevationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Elevation"
     */
    public function testElevation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "second"
     */
    public function testPropertySecond()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
