<?php
/**
 * LocalizedAlertTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  BitappSrl\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BitappSrl\OTPClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LocalizedAlertTest Class Doc Comment
 *
 * @category    Class
 * @description LocalizedAlert
 * @package     BitappSrl\OTPClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LocalizedAlertTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LocalizedAlert"
     */
    public function testLocalizedAlert()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alert_header_text"
     */
    public function testPropertyAlertHeaderText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alert_description_text"
     */
    public function testPropertyAlertDescriptionText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alert_url"
     */
    public function testPropertyAlertUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "effective_start_date"
     */
    public function testPropertyEffectiveStartDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
