<?php
/**
 * OtpApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  BitappSrl\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTP
 *
 * OTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BitappSrl\OTPClient\Test\Api;

use \BitappSrl\OTPClient\Configuration;
use \BitappSrl\OTPClient\ApiException;
use \BitappSrl\OTPClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OtpApiTest Class Doc Comment
 *
 * @category Class
 * @package  BitappSrl\OTPClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OtpApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getPlan
     *
     * Calcolo percorso.
     *
     */
    public function testGetPlan()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
